### ISSUE TITLE
phpfpm::pool::service_name and ::pool_dir should use ::phpfpm::service_name and ::pool_dir for defaults

### ISSUE THREAD

**Issue by cliles** [Slashbunny/puppet-phpfpm#12]
lf you are overriding service_name and pool_dir in ::phpfpm context, wouldn't it be nice to have that trickle down to the phpfpm::pool space as well. Seems redundant to have to specify it in to places.

As it is now, I have to do something like the following:

```
phpfpm::pool_dir: /etc/php-fpm-5.5.d
phpfpm::service_name: php-fpm-5.5
phpfpm::pools:
  test:
    pool_dir: /etc/php-fpm-5.5.d
    service_name: php-fpm-5.5
```

it would be nice to only have to do:

```
phpfpm::pool_dir: /etc/php-fpm-5.5.d
phpfpm::service_name: php-fpm-5.5
phpfpm::pools:
  test:
```

**Comment by Slashbunny** [comment]
I'd be willing to take a patch for this, I will probably not have time to implement it myself.
