### ISSUE TITLE
phpfpm::pool ensure absent not working

### ISSUE THREAD

**Issue by jsfrerot** [Slashbunny/puppet-phpfpm#19]
phpfpm::pool { 'www':
        ensure               => 'absent',
        ...
}

give the following error:
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Invalid relationship: File[/etc/php-fpm.d/www.conf] { notify => Service[php-fpm] }, because Service[php-fpm] doesn't seem to be in the catalog

**Comment by Slashbunny** [comment]
Did you include the phpfpm class prior to that? For example, this should work:

```puppet
include phpfpm

phpfpm::pool { 'www':
    ensure => 'absent',
}
```
