### ISSUE TITLE
Unknown variable: 'phpfpm::params::manage_package'

### ISSUE THREAD

**Issue by dhoppe** [Slashbunny/puppet-phpfpm#29]
If the following line is a default, it should be defined outside the case condition. 

* https://github.com/Slashbunny/puppet-phpfpm/blob/master/manifests/params.pp#L13

CentOS 7 for example provides the package php-fpm, but it is not installed by this module because the parameter manage_package is missing.

**Comment by Slashbunny** [comment]
Thanks for the report, I completely missed this in the MR that introduced the `manage_package` variable. I agree historically it's been `true` by default (prior to the variable existing) and now it's basically only `true` for Debian, which is a regression.  I'll hopefully fix this on the weekend.
