### ISSUE TITLE
Parameter "require" is redefined when pool.d content is purged

### ISSUE THREAD

**Issue by hansmi** [Slashbunny/puppet-phpfpm#35]
Commit 14970742818b9c76 seems to have introduced a bug:

`Parameter 'require' is already set on File[/etc/php/7.0/fpm/pool.d] by #<Puppet::Resource::Type:0x6f247f81> at (file: /etc/puppetlabs/code/environments/production/modules/phpfpm/manifests/init.pp, line: 63); cannot redefine (file: /etc/puppetlabs/code/environments/production/modules/phpfpm/manifests/init.pp, line: 71)`

I'm setting `phpfpm::poold_purge` to `true` via Hiera. The `require` property is set twice.

**Comment by Slashbunny** [comment]
@theosotr See above
