### ISSUE TITLE
Support for Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by rogermartensson** [Slashbunny/puppet-phpfpm#37]
Thanks for an excellent module.

PHP-FPM is at version 7.4 on Ubuntu 20.04 LTS and that means new directories.
Need to add support for 7.4 in the default paths.

A temporary solution (if found using web search) is to add a bunch of parameters.

The parameters are pid_file, package_name, service_name, config_dir, error_log and pool_dir.
I needed to add pool_dir on to the main class and on phpfpm::pool.

**Comment by Slashbunny** [comment]
If someone knows the values for all those settings on Ubuntu 20.04 LTS, they can be added in a new `elseif` in this section of the parameters file:

https://github.com/Slashbunny/puppet-phpfpm/blob/db37096c1b3f78656b3e1e2b4c08f33610e1c7a6/manifests/params.pp#L18

That should be all that is required to get it working.

**Comment by rogermartensson** [comment]
I believe that the only difference is the version number.

What I did was to create new path with the new version number. In Ubuntu 20.04 that is 7.4 instead of 7.2 in Ubuntu 18.04.

**Comment by Slashbunny** [comment]
Thanks, I downloaded the `php-fpm` deb file and inspected the contents to confirm the paths and service files are nearly identical, except with `7.4` instead of `7.2`. Released version `0.0.27` to Puppet Forge with these changes.
