### ISSUE TITLE
git tags are missing / make a new release?

### ISSUE THREAD

**Issue by bastelfreak** [Slashbunny/puppet-phpfpm#44]
Hi @Slashbunny , thanks for the great module! Is there a chance you could add the git tags for the old releases? And could you maybe do a new release? https://github.com/Slashbunny/puppet-phpfpm/commit/230224f969d66c559424f13a0c7fbf67f34870ca fixed legacy facts and that's a requirement for running on Puppet 8.

**Comment by Slashbunny** [comment]
Hi @bastelfreak . Thanks for the heads-up! My release automation broke at some point and I meant to clean that up along with all the CI cruft that accumulated over the years. I migrated to GitHub Actions using `voxpupuli/gha-puppet` as a template and added git tags to all previous releases!
